/* Modelagem Básica */
/* TABELA É UMA ENTIDADE
INFORMAÇÕES CONTIDA UMA TABELA SÃO ATRIBUTOS*/
INFORMAÇÕES DE UM CLIENTE

NOME - CARACTER(30)
CPF - NUMÉRICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE1 E FASE2 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE3 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */
CREATE DATABASE PROJETO;

/* CONECTANDOSE AO BANCO DE DADOS */
USE PROJETO;

/* CRIANDO TABELA */
CREATE TABLE CLIENTES(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES; /* SÓ EXISTE NO MYSQL */

/* DESCOBRINDO ESTRUTURA DE UMA TABELA */
DESC CLIENTES;

/*
1 CARACTER = 1 BYTE
CHAR -> NÃO VARIA O TAMANHO MAS É MAIS PERFORMÁTICO
VARCHAR -> VARIA O TAMANHO MAS É MAIS LENTO

INT -> NUMEROS INTEIROS -> MÁXIMO 11 DIGITOS POR ISSO AS VEZES CADASTRA-SE COMO VARCHAR EM ALGUNS CAMPOS NUMÉRICOS
FLOAT -> NÚMEROS REAIS FLOAT(TOTAL DE CASAS, CASAS DEPOIS DA VÍRGULA)

ENUM -> ENUMERAÇÃO -> É UM CONJUNTO DE DADOS ENUMERADO, OU SEJA, É UM NÚMERO FIXO DE DADOS -> ULTILIZAMOS 
QUANDO QUEREMOS LIMITAR O NUMERO DE DADOS EM UMA COLUNA -> EXISTE APENAS NO MySQL

LINHA INTEIRA SE CHAMA REGISTRO OU TUPLA

USAR FORMATOS DE NÚMEROS SOMENTE EM CAMPOS QUE FOREM FAZER OPERAÇÕES MATEMÁTICAS, CASO CONTRÁRIO, CADASTRAR COMO TEXTO(VARCHAR)
*/
